# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test Library 🧪🔬👩‍🔬

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x

    - name: Restore dependencies
      run: dotnet restore source/Kangaroo.sln

    - name: Build Solution
      run: dotnet build source/Kangaroo.sln --no-restore

    - name: Run Unit Tests
      run: dotnet test tests/Kangaroo.UnitTests.csproj --no-build --verbosity normal